workspace_template_dir: folder_structure/inputWorkspacesTemplate
TMD_template_dir: folder_structure/TMD_templates
L0F_Templates_Dir: folder_structure/L0F_templates
workspace_tmd_input: workspaceTMD/inputDir
workspace_tmd_output: workspaceTMD/outputDir
workspace_l0f_input: workspaceL0F/inputDir
workspace_l0f_output: workspaceL0F/outputDir
workspace_ssp_input: workspaceSSP/inputDir
workspace_ssp_output: workspaceSSP/outputDir
adquisition_folder_dest: /home/administrator/disk2tb/process_folder
